### ISSUE TITLE
RDKit Descriptors

### ISSUE THREAD

**Issue by mkowiel-ryvu** [scikit-fingerprints/scikit-fingerprints#215]
Is there a way to calculate all RDKit Descriptors? 

```python

from rdkit.Chem import Descriptors
from rdkit.ML.Descriptors import MoleculeDescriptors

FEATURES = [x[0] for x in Descriptors._descList]
RDKIT_CALCULATOR = MoleculeDescriptors.MolecularDescriptorCalculator(FEATURES)
RDKIT_DESCRIPTOR_NAMES = RDKIT_CALCULATOR.GetDescriptorNames()

def mol_to_rdkit_descriptors(mol: Chem.Mol, calculator=RDKIT_CALCULATOR):
    return calculator.CalcDescriptors(mol)

```
The descriptors are probably part of Mordred descriptors, but I'm not 100% sure. I think there is no way to select only RDKit molecular descriptors.

**Comment by j-adamczyk** [comment]
Currently not, but we will add this soon. Most of those, with maybe just a few exceptions, are part of Mordred descriptors. This will be probably implemented with [descriptastorus](https://github.com/bp-kelley/descriptastorus) descriptors and normalized weights, since z-score normalization from [this paper](https://pubs.acs.org/doi/10.1021/acs.jcim.9b00237) proved to be quite successful.

**Comment by j-adamczyk** [comment]
@mkowiel-ryvu it was implemented and will be part of the next release.
