### ISSUE TITLE
Passed data must be molecules - automate conversion

### ISSUE THREAD

**Issue by Hrovatin** [scikit-fingerprints/scikit-fingerprints#238]
For many of the fingerprints the below error occurs when attempting to call them as in the documentation on smiles list.
```
Passed data must be molecules (rdkit.Chem.rdChem.Mol instances) and each must have conf_id property set. You can use ConformerGenerator to add them.
```
To make the package more user-friendly, I would suggest transforming similes automatically to molecules.

**Comment by j-adamczyk** [comment]
@Hrovatin this is an intended behavior. It does not only require transforming SMILES to molecules, but rather the entire conformer generation.

Creating molecules from SMILES is not straightforward itself, and allowing SMILES input already can be tricky, since it doesn't have one common standard. We considered not allowing SMILES input at all, and requiring creating molecules explicitly, but finally settled for simplified automatic SMILES -> `Mol` internal parsing. Adding conformations on top of this is yet another layer of complexity that is very much problem- and user-dependent.

The main issue is that molecules should typically be cleaned and standardized before computing fingerprints. When calling `MolFromSmiles`, RDKit already performs an entire sanitization pipeline: https://www.rdkit.org/docs/RDKit_Book.html#molecular-sanitization. However, many more standardization steps are possible, see e.g. https://github.com/rdkit/rdkit/blob/master/Docs/Notebooks/MolStandardize.ipynb, or tautomer canonicalization https://rdkit.blogspot.com/2020/01/trying-out-new-tautomer.html. We expose some very basic standardization in `MolStandardizer` class.

Conformer generation is another issue on top of all this. In particular, it can fail much more easily than parsing 2D molecule from SMILES. `ConformerGenerator` exposes some reasonable defaults, but it is still error-prone and user should make informed decisions about its results. Cleaned molecules decrease the change of failures. For example, we couldn't successfully generate conformers for full dataset for any of MoleculeNet datasets. On top of this, you have force field optimization - you can use it or not, and there are different algorithms. Disconnected molecules are also highly problematic, since RDKit does not model interactions between components, while e.g. CONFORGE (https://pubs.acs.org/doi/10.1021/acs.jcim.3c00563) can do that. This is also why `ConformerGenerator` has `.transform_x_y()` method. And finally, it can take a lot of time, often a dozen minutes or more for a typical dataset, while parsing SMILES as `Mol` is almost free.

Overall, it's a complex issue. I think that error message is quite clear, although we could definitely add more examples. The code is something like this:
```
smiles_list = ...
labels = ...

mol_from_smiles = MolFromSmilesTransformer()
mols = mol_from_smiles.transform(smiles_list)

# note that this can filter out some molecules!
conf_gen = ConformerGenerator(errors="filter")
mols, y = conf_gen.transform_x_y(mols, labels)

fp = USRFingerprint()
X = fp.transform(mols)
```

I hope this explains the rationale. Let us know if you have any further questions in this regard.

**Comment by Hrovatin** [comment]
Thank you, it would be great if this could be explained in the readme besides the current smiles-input example; including the check for whether fingerprint requires it, e.g. ` if fingerprint_encoder.requires_conformers`

**Comment by j-adamczyk** [comment]
Sure, I've added more examples in https://github.com/scikit-fingerprints/scikit-fingerprints/pull/245
